name: Deploy SharePoint Web Part

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js 14.x, Python 2, and Gulp
      - name: Setup Node.js 14.x, Python 2, and Gulp
        run: |
          # Install NVM (Node Version Manager) - Latest Stable Version
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          # Load NVM into the shell session
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

          # Install Node.js 14.x
          nvm install 14
          nvm use 14

          # Verify Node.js and npm installation
          echo "Node.js version:"
          node -v
          echo "npm version:"
          npm -v

          # Install Python 2
          sudo apt-get update
          sudo apt-get install -y python2
          # Create a symbolic link so that 'python' points to 'python2'
          sudo ln -sf /usr/bin/python2 /usr/bin/python

          # Verify Python installation
          echo "Python version:"
          python --version

          # Install Gulp globally (version 3.9.1)
          npm install -g gulp@3.9.1

          # Verify Gulp installation
          echo "Gulp version:"
          gulp -v

      # 3. Install Project Dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Build the Project
      - name: Build the Package
        run: gulp build

      # 5. Bundle the Project
      - name: Bundle the Package
        run: gulp bundle

      # 6. Package the Solution
      - name: Package Solution
        run: gulp package-solution

      # 7. Upload the Packaged .sppkg File as an Artifact
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sharepoint-package
          path: ./sharepoint/solution/*.sppkg

      # 8. Install PnP PowerShell Module
      - name: Install PnP PowerShell
        shell: pwsh
        run: Install-Module -Name PnP.PowerShell -Force -Scope CurrentUser

      # 9. Deploy to SharePoint App Catalog
      - name: Deploy to SharePoint App Catalog
        shell: pwsh
        env:
          SP_APP_CATALOG_URL: ${{ secrets.SP_APP_CATALOG_URL }}
          SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
          SP_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
        run: |
          # Connect to SharePoint App Catalog using Client ID and Secret
          Connect-PnPOnline -Url $env:SP_APP_CATALOG_URL -ClientId $env:SP_CLIENT_ID -ClientSecret $env:SP_CLIENT_SECRET -Tenant "xllearnings.sharepoint.com"

          # Deploy the SPFx package to the App Catalog
          $packagePath = Get-ChildItem -Path "./sharepoint/solution/" -Filter *.sppkg | Select-Object -First 1
          if ($packagePath) {
            Add-PnPApp -Path $packagePath.FullName -Scope Tenant -Overwrite
          } else {
            Write-Error "No .sppkg file found in the solution folder."
            exit 1
          }

          # Deploy the app if it's not already deployed
          $app = Get-PnPApp | Where-Object { $_.Title -eq "sharepoint-1" } # Replace "YourAppName" with your actual app name
          if ($app -and -not $app.IsDeployed) {
            Install-PnPApp -Identity $app.Id -Scope Tenant
          }
